
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Shj123456!
    url: jdbc:mysql://188.131.135.224:3306/award?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: -1
    filters: stat,wall,slf4j,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMil=3000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

server:
  port: 8888

mybatis:
  type-aliases-package: com.zyl.award.*
  mapper-locations: classpath:mapperbase/*.xml
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - com.zyl.award.commons.mapperbase.MyMapper
  notEmpty: true
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true    #pageNo<=0时默认为1
  supportMethodsArguments: true
  params: count=countSql

web:
  upload:
    file:
      path: D:/tmp/file
    pic:
      path: D:/tmp/pic
    excel:
      path: D:/tmp/excel

